export const FACE_REC_BOXES_PENDING = 'FACE_REC_BOXES_PENDING';
export const FACE_REC_BOXES_SUCCESS = 'FACE_REC_BOXES_SUCCESS';
export const FACE_REC_BOXES_FAILED = 'FACE_REC_BOXES_FAILED';
export const CLEAR_FACE_REC_BOXES = 'CLEAR_FACE_REC_BOXES';

export const SIGIN_IN_USER_SUCCESS = 'SIGIN_IN_USER_SUCCESS';
export const SIGIN_IN_USER_PENDING = 'SIGIN_IN_USER_PENDING';
export const SIGIN_IN_USER_FAILED = 'SIGIN_IN_USER_FAILED';
export const SIGIN_OUT_USER = 'SIGIN_OUT_USER';
